# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 441053cbc02ae5f1d5ff61ee19418e8d1a5dd9daeb2295f991468e6c9a4980e932c7be90480b56de3aa9b7209abc7cdb23c49670278368ae1503e2e198959755

test:
  secret_key_base: 2211163a8cde6bef20998ca1e9b85b72871e29dfd934d6afbbdc3c147a40e611e373e2c4bcf1a9de1e9d288f804f3b9f261852024d27a134008fb8e1b84cbb08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
